version: '3.9'

services:
    java_app:
        container_name: java_app
        image: java-app:1.0.0
        build: .
        ports:
            - 8080:8080
        depends_on:
            - java_db
            
java_db:
    container_name: java_db
    image: mysql:8
    ports:
        - 3306:3306
        